### ISSUE TITLE
Can't get this extension working

### ISSUE THREAD

**Issue by kandyman2017** [itayperl/jisho-ojad#1]
I don't know why, but I have tried this several times. After I install the extension via the Chrome Extension store, I search for words on Jisho.org but the pitch-accent is never displayed. I have noticed several reviews on the store of people who say that it doesn't work for them either.

What info do you  need to help identify the problem? The only thing I noticed was that the extension icon in the toolbar was 'greyed out'.

**Comment by itayperl** [comment]
I've just released a new version (v1.3) to the webstore that should fix the issue (missing support for https://). I've had that fix locally for a while now but forgot to release it... :)

You can force the update by going to chrome://extensions and pressing "update".
