### ISSUE TITLE
There is no feedback when there are no results from OJAD

### ISSUE THREAD

**Issue by munshkr** [itayperl/jisho-ojad#2]
First of all, thanks for the extension! I'm just getting into japanese phonetics, and this helps a lot.

I've noticed that when it fails to find an exact word, it doesn't do anything else. At first I thought there was something wrong, but looking at the console I found out that there were no exact results from OJAD. For example, if you look up [学院 in jisho](https://jisho.org/search/%E5%AD%A6%E9%99%A2), OJAD returns entries for 大学院 and 大学院生 only, and it does not match any entry in the jisho page.
As a suggestion, it'd be good to add a `<span>` saying "No phonetic information" or something like that.

**Comment by itayperl** [comment]
Added in v1.6. Thanks @munshkr!
